### PR TITLE
Update CIP-82 to use CIP-88 namespace

### PR DESCRIPTION
**Pull request by PaulLeCam**
CIP-88 issue: https://github.com/ceramicnetwork/CIP/issues/88

### CODE REVIEW

**Review by oed — COMMENTED** [review]
Can you include CIP-88 as well? I guess CIP-82 should state that it requires 88?

**Comment by PaulLeCam** [comment]
Yes good idea, I added the requirement to the header.

**Comment by oed** [comment]
But do you mind also adding CIP-88 as part of this PR? Would be good if it's finable in the INDEX.md if it's a requirement here.

**Comment by PaulLeCam** [comment]
I could but I thought the flow would be first discussing/merging CIP 88 and then updating 82 and 85, no? Basically I'd like to make sure possible comments about 88 are addressed before making further changes to other CIPs.

I don't mind adding 88 in this PR if it makes things simpler, just want to make sure it doesn't slow the process down.

**Comment by oed** [comment]
I think it's fine to merge drafts before much discussion. Drafts can always easily be updated with a new PR if needed.

**Review by oed — APPROVED** [review]

**Pull request merged**
